#Placement prediction



#Description about placement prediction


The Placement of students is one of the most important objective of an educational institution. Reputation and yearly admissions of an institution invariably depend on the placements it provides it students with. That is why all the institutions, arduously, strive to strengthen their placement department so as to improve their institution on a whole. Any assistance in this particular area will have a positive impact on an institution’s ability to place its students. This will always be helpful to both the students, as well as the institution.



#objective of placement prediction


The aim of project is to predict whether the student will be recruited in campus placements or not based on the available factors in the dataset.

#Understand about dataset.


Variables in dataset are:


 1.Student ID

 2.CGPA

 3.IQ

 4.Placement

#Import libraries

In [6]:
import pandas as pd
import numpy as np

#Import DataFrame

In [7]:
df = pd.read_csv('https://github.com/YBI-Foundation/Dataset/raw/main/Placement.csv')

#Get first five rows of DataFrame

In [8]:
df.head()

Student_ID  CGPA   IQ  Placement
0           1   6.8  123          1
1           2   5.9  106          0
2           3   5.3  121          0
3           4   7.4  132          1
4           5   5.8  142          0

#Get information of DataFrame

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Student_ID  100 non-null    int64  
 1   CGPA        100 non-null    float64
 2   IQ          100 non-null    int64  
 3   Placement   100 non-null    int64  
dtypes: float64(1), int64(3)
memory usage: 3.2 KB


#Get the summary statics

In [10]:
df.describe ()

Student_ID        CGPA          IQ   Placement
count  100.000000  100.000000  100.000000  100.000000
mean    50.500000    5.991000  123.580000    0.500000
std     29.011492    1.143634   39.944198    0.502519
min      1.000000    3.300000   37.000000    0.000000
25%     25.750000    5.075000  101.500000    0.000000
50%     50.500000    6.000000  127.500000    0.500000
75%     75.250000    6.900000  149.000000    1.000000
max    100.000000    8.500000  233.000000    1.000000

#Get columns names

In [11]:
df.columns

Index(['Student_ID', 'CGPA', 'IQ', 'Placement'], dtype='object')

#Set shape of DataFrame

In [12]:
df.shape

(100, 4)

#Get unique values (class Or label) in y variable

In [13]:
df['Placement'].value_counts()

Placement
1    50
0    50
Name: count, dtype: int64

In [14]:
df.groupby('Placement').mean()

Student_ID   CGPA      IQ
Placement                           
0               46.32  5.056  126.88
1               54.68  6.926  120.28

#Define y ( depended or label or target variable) and x (independent or features Or attribute variable)

In [15]:
y = df['Placement']

In [16]:
y.shape

(100,)

In [17]:
 y

0     1
1     0
2     0
3     1
4     0
     ..
95    0
96    0
97    1
98    1
99    1
Name: Placement, Length: 100, dtype: int64

In [20]:
 x= df[['CGPA', 'IQ']]

In [19]:
 x.shape

(100, 2)

In [ ]:
x

CGPA   IQ
0    6.8  123
1    5.9  106
2    5.3  121
3    7.4  132
4    5.8  142
..   ...  ...
95   4.3  200
96   4.4   42
97   6.7  182
98   6.3  103
99   6.2  113

[100 rows x 2 columns]

#Get x variable standardized

In [21]:
from sklearn.preprocessing import StandardScaler

In [22]:
ss = StandardScaler()

In [23]:
X = ss.fit_transform(x)

In [24]:
X

array([[ 0.71095807, -0.01459341],
       [-0.0799718 , -0.44233119],
       [-0.60725838, -0.0649155 ],
       [ 1.23824465,  0.21185601],
       [-0.16785289,  0.46346647],
       [ 0.97460136, -1.90167186],
       [-0.25573399,  0.48862751],
       [-0.87090167, -1.52425617],
       [ 0.0957904 ,  0.81572111],
       [-0.78302057, -1.44877303],
       [ 0.0079093 , -1.977155  ],
       [ 0.79883917,  0.36282228],
       [-0.51937728,  0.38798333],
       [ 0.35943369, -0.19072073],
       [ 0.0957904 , -0.51781433],
       [-0.78302057,  1.31894203],
       [-0.69513948,  2.52667224],
       [-2.36488031,  1.49506935],
       [-1.74971264, -0.59329747],
       [-0.69513948,  0.21185601],
       [ 0.53519588, -0.09007654],
       [ 0.97460136,  0.68991588],
       [-0.95878277, -0.09007654],
       [-1.13454496, -0.92039106],
       [-1.13454496, -0.0649155 ],
       [-0.87090167, -0.81974688],
       [ 0.88672027,  1.89764609],
       [ 0.0079093 ,  0.01056764],
       [-0.69513948,

#Get Train Test Split

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3,stratify = y, random_state=2529)

In [27]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((70, 2), (30, 2), (70,), (30,))

#Get model train

In [28]:
from sklearn.linear_model import LogisticRegression

In [29]:
lr = LogisticRegression()

In [30]:
lr.fit(X_train, y_train)

LogisticRegression()

#Get model prediction

In [31]:
y_pred = lr.predict(X_test)

In [32]:
y_pred.shape

(30,)

In [33]:
y_pred

array([1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 1])

#Get probability of each predicted class

In [34]:
lr.predict_proba(X_train)

array([[9.95475458e-01, 4.52454227e-03],
       [8.50640830e-02, 9.14935917e-01],
       [1.15922088e-01, 8.84077912e-01],
       [5.08192106e-01, 4.91807894e-01],
       [6.65194097e-01, 3.34805903e-01],
       [2.42923345e-01, 7.57076655e-01],
       [2.76387478e-02, 9.72361252e-01],
       [8.58545681e-01, 1.41454319e-01],
       [4.51386285e-02, 9.54861371e-01],
       [9.58734411e-03, 9.90412656e-01],
       [3.96660453e-01, 6.03339547e-01],
       [7.21930352e-01, 2.78069648e-01],
       [6.96790677e-01, 3.03209323e-01],
       [9.51153731e-01, 4.88462694e-02],
       [4.43318365e-01, 5.56681635e-01],
       [9.30173962e-01, 6.98260379e-02],
       [9.98923652e-01, 1.07634848e-03],
       [3.64861326e-02, 9.63513867e-01],
       [6.47346507e-01, 3.52653493e-01],
       [9.85760629e-01, 1.42393710e-02],
       [6.05721744e-02, 9.39427826e-01],
       [5.27683671e-03, 9.94723163e-01],
       [2.79829453e-02, 9.72017055e-01],
       [8.85716224e-01, 1.14283776e-01],
       [9.934645

#Get future predictions

Let's select a random sample from existing dataset as new value

Steps to follow:

 1.Extract a random row using sample function

2.seprate X and Y

3.Standardize X

4.predict

In [35]:
X_new = df.sample(1)

In [36]:
X_new

Student_ID  CGPA   IQ  Placement
17          18   3.3  183          0

In [37]:
X_new.shape

(1, 4)

In [38]:
X_new = X_new.drop(['Student_ID', 'Placement'], axis= 1)

In [39]:
X_new

CGPA   IQ
17   3.3  183

In [40]:
X_new.shape

(1, 2)

In [41]:
X_new = ss.fit_transform(X_new)

In [42]:
y_pred_new = lr.predict(X_new)

In [43]:
y_pred_new

array([0])

In [44]:
lr.predict_proba(X_new)

array([[0.5136401, 0.4863599]])

#Evaluate model

In [45]:
from sklearn.metrics import accuracy_score

In [47]:
accuracy_score(y_test,y_pred)

0.9666666666666667